name: Docker Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    # Only run it when the push is to the countymicro/docker-test-saml-idp repo. Otherwise the secrets for pushing to
    # Docker will not be available.
    if: github.repository_owner == 'countymicro'
    runs-on: ubuntu-latest
    environment: Docker Hub
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          repository: countymicro/docker-idp
          tags: latest
